### ISSUE TITLE
Cleanup doesn't work with prefix

### ISSUE THREAD

**Issue by jplitza** [lordsutch/btrfs-backup#10]
If you specify `--snapshot-prefix foo`, then the cleanup of old backups doesn't work:
```
backup complete
Traceback (most recent call last):
  File "/opt/btrfs-backup/btrfs-backup.py", line 224, in <module>
    delete_old_backups(backuploc,NUM_BACKUPS)
  File "/opt/btrfs-backup/btrfs-backup.py", line 115, in delete_old_backups
    bak_dir_to_remove = datestr(find_old_backup(bak_dir_time_objs, 0))
  File "/opt/btrfs-backup/btrfs-backup.py", line 84, in find_old_backup
    min_val = min(tmp) # find minimum time value
ValueError: min() arg is an empty sequence
```
This is caused by [line 110](https://github.com/lordsutch/btrfs-backup/blob/master/btrfs-backup.py#L110) in `delete_old_backups`, where `time.strptime()` is applied to the snapshot directory names with the matching pattern `%Y%m%d-%H%M%S`, ignoring the prefix and thus not matching any directories:
```
                bak_dir_time_objs.append(time.strptime(directory, '%Y%m%d-%H%M%S'))
```

**Comment by lordsutch** [comment]
Issue should now be fixed - thanks!
