### ISSUE TITLE
Instead of caveat, refer to flock(1)

### ISSUE THREAD

**Issue by hoxu** [lordsutch/btrfs-backup#4]
Instead of contemplating reimplementing locking in btrfs-backup, you could just tell people to use flock(1) utility for locking. flock -n is perfect for this usecase :)

**Comment by hale** [comment]
Like this?

    #!/bin/sh
    flock -n /tmp/btrfs-backup.lockfile -c ionice -c 3 /location/of/btrfs-backup.py /source /destination

**Comment by hoxu** [comment]
With `-c` you need to quote the command flock passes to shell. I personally just use it without the -c parameter:

    flock -n /tmp/foo.lockfile command param1 param2 etc

Perfect for potentially long-running jobs like backups :)

**Comment by lordsutch** [comment]
Added instructions to README.md.

**Comment by hale** [comment]
Thank you :)
